---
- name: Get AKS clusters and node pools information
  hosts: localhost
  gather_facts: false
  vars:
    resource_group: "myResourceGroup"  # Change this to your resource group name

  tasks:
    # Task 1: Gather all AKS clusters in the specified resource group
    - name: List all AKS clusters in the resource group
      azure.azcollection.azure_rm_aks_info:
        resource_group: "{{ resource_group }}"
      register: aks_clusters

    # Task 2: Display raw aks_clusters output for debugging (optional)
    - name: Display raw aks_clusters output for debugging
      debug:
        var: aks_clusters

    # Task 3: Extract AKS cluster names using json_query
    - name: Extract AKS cluster names
      set_fact:
        aks_cluster_names: "{{ aks_clusters.aks | json_query('[].name') }}"

    - name: Display the AKS cluster names array
      debug:
        var: aks_cluster_names

    # Task 4: Display Kubernetes version for each AKS cluster using the filtered list
    - name: Display Kubernetes version for each AKS cluster
      debug:
        msg: "Cluster: {{ item.name }} is on kuberenets version in: {{ item.current_kubernetes_version }}"
      loop: "{{ aks_clusters.aks }}"
      loop_control:
        label: "{{ item.name }}"

    # Task 5: Get node pools for each AKS cluster
    - name: Get node pools for each AKS cluster
      azure.azcollection.azure_rm_aksagentpool_info:
        resource_group: "{{ resource_group }}"
        cluster_name: "{{ item }}"
      loop: "{{ aks_cluster_names }}"
      register: node_pools

    # Task 6: Filter and extract relevant node pool information using json_query
    - name: Extract node pool details for each AKS cluster
      set_fact:
        filtered_node_pools: >-
          {{
            node_pools.results
            | json_query('[].aksagentpools[*].{cluster_name: item, node_pool_name: name, kubernetes_version: orchestrator_version}')
          }}

    # Task 7: Display filtered node pool information
    - name: Display filtered node pool information
      debug:
        var: filtered_node_pools
