- name: Upgrade Azure AKS Cluster
  hosts: localhost
  tasks:
    - name: Upgrade AKS cluster version
      azure.azcollection.azure_rm_aks:
        resource_group: "<your-resource-group>"
        name: "<your-cluster-name>"
        kubernetes_version: "1.30.3"
        state: present
