---
- name: Upgrade AKS Node Pool
  hosts: localhost
  collections:
    - azure.azcollection
  tasks:
    - name: Upgrade AKS Node Pool
      azure.azcollection.azure_rm_aksagentpool:
        resource_group: "{{ resource_group }}"
        cluster_name: "{{ cluster_name }}"
        name: "{{ node_pool_name }}"
        orchestrator_version: "{{ kubernetes_version }}"
        state: present
      register: nodepool_result

    - name: Display the result
      debug:
        var: nodepool_result
