---
- name: Upgrade Azure AKS Cluster
  hosts: localhost
  tasks:
    - name: Upgrade AKS cluster version
      azure.azcollection.azure_rm_aks:
        resource_group: "myAKSResourceGroup2e9442"
        name: "myAKSCluster2e9442"
        kubernetes_version: "1.30.3"
        state: present
