---
- name: Upgrade Azure AKS Cluster
  hosts: localhost
  collections:
    - azure.azcollection
  tasks:
    - name: Upgrade AKS cluster version
      azure.azcollection.azure_rm_aks:
        resource_group: "myAKSResourceGroupe55117"
        name: "myAKSClustere55117"
        kubernetes_version: "1.30.4"
        dns_prefix: "myAKSClust-myAKSResourceGro-408895"
        agent_pool_profiles: 
          - name: "nodepool1"
            count: 1
            vm_size: "Standard_DS2_v2"
            os_type: "Linux"
            os_disk_size_gb: 128
        enable_rbac: true    
        state: present
