---
- name: Collect services running on Linux hosts and generate HTML report
  hosts: all
  become: yes
  gather_facts: no
  vars:
    report_file: "/var/lib/awx/services_report.html"  # Path where Ansible Tower can write files

  tasks:
    - name: Collect services status
      command: systemctl list-units --type=service --no-pager --no-legend
      register: services_output
      ignore_errors: yes

    - name: Create or update services data file for each host
      copy:
        content: |
          {% for line in services_output.stdout_lines %}
            {{ line }}
          {% endfor %}
        dest: "/tmp/{{ inventory_hostname }}_services.txt"

    - name: Collect services data from all hosts
      fetch:
        src: "/tmp/{{ inventory_hostname }}_services.txt"
        dest: "/tmp/"
        flat: yes

    - name: Aggregate services data
      local_action: command cat /tmp/*_services.txt
      register: combined_services_output
      run_once: true

    - name: Build services data dictionary
      set_fact:
        services_data: |
          {% set data = {} %}
          {% for host in groups['all'] %}
            {% set services = lookup('file', '/tmp/' + host + '_services.txt').split('\n') %}
            {% set data = data | combine({host: services}) %}
          {% endfor %}
          {{ data }}

    - name: Generate HTML report from template
      template:
        src: templates/report.html.j2
        dest: "{{ report_file }}"
      run_once: true
      delegate_to: localhost

    - name: Clean up temporary files on local machine
      local_action: file
      args:
        path: "/tmp/{{ item }}_services.txt"
        state: absent
      with_items: "{{ groups['all'] }}"
      run_once: true

    - name: Notify about the report location
      debug:
        msg: "Services report generated at {{ report_file }}"
      run_once: true
