---
- name: Check web services and generate an HTML report
  hosts: localhost
  gather_facts: no
  vars:
    services:
      - { name: "Service 1", url: "https://example.com/api1", response_threshold: 2 }
      - { name: "Service 2", url: "https://example.com/api2", response_threshold: 1.5 }
      - { name: "Service 3", url: "https://example.com/api3", response_threshold: 3 }
    html_report: "/tmp/service_report.html"
  
  tasks:
    - name: Check web service response status and time
      uri:
        url: "{{ item.url }}"
        return_content: no
        timeout: 10
        status_code: 200
      register: response
      loop: "{{ services }}"
      loop_control:
        label: "{{ item.name }}"
      failed_when: response.status is undefined or response.elapsed is undefined

    - name: Build results list
      set_fact:
        service_results: "{{ service_results | default([]) + [{
            'name': item.item.name,
            'url': item.item.url,
            'status_code': item.status,
            'response_time': item.elapsed.total_seconds,
            'status': (item.status != 200) | ternary('red', (item.elapsed.total_seconds > item.item.response_threshold) | ternary('orange', 'green'))
        }] }}"
      loop: "{{ response.results }}"
    
    - name: Generate HTML report
      template:
        src: service_report_template.html.j2
        dest: "{{ html_report }}"
    
    - name: Display the location of the generated report
      debug:
        msg: "HTML report generated at {{ html_report }}"
